language: python
dist: bionic

matrix:
  include:
    # The pypy tests are slow, so we list them first
{%- if cookiecutter.earliest_supported_python <= "3.6" %}
    - python: pypy3.6-7.2.0
    - language: generic
      env: PYPY_NIGHTLY_BRANCH=py3.6
{%- if cookiecutter.earliest_supported_python <= "3.5" %}
    - python: 3.5-dev
{%- endif %}
{%- if cookiecutter.earliest_supported_python <= "3.6" %}
    - python: 3.6-dev
{%- endif %}
{%- if cookiecutter.earliest_supported_python <= "3.7" %}
    - python: 3.7-dev
{%- endif %}
{%- if cookiecutter.earliest_supported_python <= "3.8" %}
    - python: 3.8-dev
{%- endif %}
    - python: nightly

script:
  - ./ci.sh

branches:
  except:
    - /^dependabot/.*/
