name: CI

on: [pull_request]

jobs:
  Windows:
{%- raw %}
    name: 'Windows (${{ matrix.python }}, ${{ matrix.arch }}${{ matrix.extra_name }})'
{%- endraw %}
    timeout-minutes: 20
    runs-on: 'windows-latest'
    strategy:
      fail-fast: false
      matrix:
        python:
{%- if cookiecutter.earliest_supported_python <= "3.6" %}
          - '3.6'
{%- endif %}
{%- if cookiecutter.earliest_supported_python <= "3.7" %}
          - '3.7'
{%- endif %}
{%- if cookiecutter.earliest_supported_python <= "3.8" %}
          - '3.8'
{%- endif %}
        arch: ['x86', 'x64']
{%- raw %}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '${{ matrix.python }}'
          architecture: '${{ matrix.arch }}'
      - name: Run tests
        run: ./ci.sh
        shell: bash
        env:
          # Should match 'name:' up above
          JOB_NAME: 'Windows (${{ matrix.python }}, ${{ matrix.arch }})'
{%- endraw %}

  Linux:
{%- raw %}
    name: 'Linux (${{ matrix.python }}${{ matrix.extra_name }})'
{%- endraw %}
    timeout-minutes: 10
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        python:
{%- if cookiecutter.earliest_supported_python <= "3.6" %}
          - '3.6'
{%- endif %}
{%- if cookiecutter.earliest_supported_python <= "3.7" %}
          - '3.7'
{%- endif %}
{%- if cookiecutter.earliest_supported_python <= "3.8" %}
          - '3.8'
{%- endif %}
        check_docs: ['0']
        check_lint: ['0']
        extra_name: ['']
        include:
          - python: '3.8'
            check_docs: '1'
            extra_name: ', check docs'
          - python: '3.8'
            check_lint: '1'
            extra_name: ', formatting and linting'
{%- raw %}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '${{ matrix.python }}'
      - name: Run tests
        run: ./ci.sh
        env:
          CHECK_DOCS: '${{ matrix.check_docs }}'
          CHECK_LINT: '${{ matrix.check_lint }}'
          # Should match 'name:' up above
          JOB_NAME: 'Linux (${{ matrix.python }}${{ matrix.extra_name }})'
{%- endraw %}

  macOS:
{%- raw %}
    name: 'macOS (${{ matrix.python }})'
{%- endraw %}
    timeout-minutes: 10
    runs-on: 'macos-latest'
    strategy:
      fail-fast: false
      matrix:
        python:
{%- if cookiecutter.earliest_supported_python <= "3.6" %}
          - '3.6'
{%- endif %}
{%- if cookiecutter.earliest_supported_python <= "3.7" %}
          - '3.7'
{%- endif %}
{%- if cookiecutter.earliest_supported_python <= "3.8" %}
          - '3.8'
{%- endif %}
{%- raw %}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '${{ matrix.python }}'
      - name: Run tests
        run: ./ci.sh
        env:
          # Should match 'name:' up above
          JOB_NAME: 'macOS (${{ matrix.python }})'
{%- endraw %}
